# Generated by Django 4.0.3 on 2022-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.CharField(max_length=2083)),
                ('order_qty', models.IntegerField()),
                ('shipment_date', models.DateTimeField()),
            ],
        ),
    ]
